services:
  - type: web
    name: social-media-video
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    publishPath: .next
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
