// src/lib/templates/library.ts

import type { SocialPlatform } from '../../types'

export type TemplateCategory =
  | 'product_launch' | 'tutorial' | 'viral_hook' | 'behind_scenes'
  | 'testimonial' | 'trending' | 'educational' | 'challenge' | 'promo'
  | 'naija_fiction' | 'naija_culture' | 'afrobeats' | 'street_life' | 'hustle'

export interface ContentTemplate {
  id: string
  name: string
  category: TemplateCategory
  platform: SocialPlatform[]
  contentType: 'video' | 'image' | 'both'
  tier: 'free' | 'basic' | 'pro'
  hook: string
  structure: string[]
  visualPrompt: string
  captionTemplate: string
  hashtags: string[]
  estimatedViews: string
  bestTime: string
  emoji: string
}

export const TEMPLATE_LIBRARY: ContentTemplate[] = [
  // ─── Viral Hooks ────────────────────────────────────────────────
  {
    id: 'hook-pov-story',
    name: 'POV Story Hook',
    category: 'viral_hook',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'POV: You just discovered something that changed everything...',
    structure: ['Open with POV statement on screen', 'Cut to reaction/reveal', '3 quick benefits', 'CTA: "Follow for more"'],
    visualPrompt: 'Cinematic close-up face reveal, dramatic lighting, shallow depth of field, ASMR-style quiet',
    captionTemplate: 'POV: {topic} changed my life 👀 Here\'s what happened...\n\n{main_content}\n\nDouble tap if this helped you! 💛',
    hashtags: ['pov', 'viral', 'trending', 'fyp', 'foryou'],
    estimatedViews: '10K - 500K',
    bestTime: '7pm - 10pm',
    emoji: '👀',
  },
  {
    id: 'hook-nobody-talks',
    name: 'Nobody Talks About This',
    category: 'viral_hook',
    platform: ['tiktok', 'instagram', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: 'Nobody talks about this but {topic} is...',
    structure: ['State secret/controversial claim', 'Build suspense', 'Reveal with proof', 'Engage: "Was I wrong?"'],
    visualPrompt: 'Person speaking directly to camera, dramatic pause, text overlay animation, trending audio energy',
    captionTemplate: 'Nobody talks about this but {topic}... 🤫\n\n{revelation}\n\nAm I wrong? Comment below 👇',
    hashtags: ['nobodytalkabout', 'secrets', 'truth', 'viral', 'fyp'],
    estimatedViews: '50K - 2M',
    bestTime: '12pm - 2pm',
    emoji: '🤫',
  },

  // ─── Naija Fiction / Cinematic Shorts ────────────────────────────
  {
    id: 'naija-nollywood-short',
    name: 'Nollywood Short Drama',
    category: 'naija_fiction',
    platform: ['tiktok', 'instagram', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: 'She didn\'t know her husband was living a double life until that night...',
    structure: [
      'Open mid-scene with dramatic confrontation',
      'Flashback reveal (1-2 quick cuts)',
      'Emotional peak moment with close-up',
      'Cliffhanger ending: "Part 2 tomorrow..."',
    ],
    visualPrompt: 'Cinematic Nigerian living room, dramatic warm lighting, close-up faces showing shock and betrayal, Nollywood aesthetic, rich Ankara fabric, authentic Lagos interior, 4K film look',
    captionTemplate: 'EPISODE {number}: {title} 🎬\n\nWhen {scenario}...\n\nThis is based on a true story shared with permission.\n\nComment "MORE" for Part {next} 👇\n\n{emotional_note}',
    hashtags: ['nollywood', 'naijadrama', 'nigerianstory', 'africancontent', 'shortfilm', 'nigeriatiktok'],
    estimatedViews: '100K - 5M',
    bestTime: '8pm - 11pm',
    emoji: '🎭',
  },
  {
    id: 'naija-village-mystery',
    name: 'Village Mystery / Folklore',
    category: 'naija_fiction',
    platform: ['tiktok', 'youtube', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'In my village, there is a tree nobody touches... until my cousin dared to.',
    structure: [
      'Narrator voice-over over establishing shot of village',
      'Build atmosphere with mysterious detail',
      'Rising tension — something goes wrong',
      'Supernatural or unexpected twist',
      'Moral/ending that resonates with African worldview',
    ],
    visualPrompt: 'Dense Nigerian forest at dusk, village path with mud huts, firelight flickering, mist, mystical atmospheric lighting, aerial shot slowly descending, folk tale aesthetic, deep shadows',
    captionTemplate: 'This story was passed down from my grandmother 👁️\n\n{story_opening}...\n\nHave you heard stories like this from your village? Share below 👇\n\n#truenaijastory',
    hashtags: ['naijastories', 'africanfolklore', 'nigerianmystery', 'villagestories', 'africanmythology'],
    estimatedViews: '200K - 10M',
    bestTime: '9pm - 12am',
    emoji: '🌿',
  },
  {
    id: 'naija-hustle-origin',
    name: 'From Nothing Story',
    category: 'naija_fiction',
    platform: ['youtube', 'tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'I started with ₦5,000. This is how I built everything from scratch.',
    structure: [
      'Humble beginning — show the struggle honestly',
      'The turning point (one decision that changed everything)',
      'Montage of growth with timestamps',
      'Where they are now — emotional reveal',
      'Message to the younger generation',
    ],
    visualPrompt: 'Lagos street hustle, Alaba market, roadside food stall, small workshop, then cut to modern office or store — time-lapse transformation, warm amber tones, authentic Nigerian environments',
    captionTemplate: 'Nobody believed in me when I started.\n\n{struggle}\n\nToday? {achievement}\n\nIf you\'re still in your ₦5,000 era — keep going. Your chapter isn\'t over. 🙏\n\n{cta}',
    hashtags: ['fromnothingstory', 'naijahustle', 'nigerianentrepreneur', 'lagoshustle', 'successstory', 'motivation'],
    estimatedViews: '50K - 2M',
    bestTime: '7am - 9am',
    emoji: '💪',
  },
  {
    id: 'naija-returnee-shock',
    name: 'Returnee Culture Shock',
    category: 'naija_fiction',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'I left Nigeria for 5 years. Coming back felt like a completely different country.',
    structure: [
      'Airport arrival — immediate sensory overload',
      'First surprise (something changed)',
      'Funny/emotional reconnection moment',
      'Reflection: what Nigeria taught you abroad',
    ],
    visualPrompt: 'Lagos Murtala Muhammad Airport, outside Arrivals with yellow danfo buses, chaotic beautiful energy, person in foreign outfit navigating the crowd, golden hour light, vibrant street colors',
    captionTemplate: 'Year one abroad vs year five abroad vs coming home 🇳🇬\n\n{observation}\n\nNigeria will humble you every time. 😂\n\nWhich returnee moment hit different? 👇',
    hashtags: ['japa', 'naijaindiaspora', 'returnee', 'nigerianabroad', 'comingback', 'naijatiktok'],
    estimatedViews: '80K - 3M',
    bestTime: '6pm - 9pm',
    emoji: '✈️',
  },

  // ─── Street Life / Everyday Nigeria ──────────────────────────────
  {
    id: 'street-food-asmr',
    name: 'Street Food ASMR',
    category: 'street_life',
    platform: ['tiktok', 'instagram', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: 'The sound of suya being sliced at midnight Lagos... pure satisfaction.',
    structure: [
      'Open on close-up hands preparing food with ambient street noise',
      'Sizzle/chop sounds at front — no voice needed',
      'Food being plated or wrapped in newspaper',
      'First bite or customer reaction',
      'Location + price tag text overlay',
    ],
    visualPrompt: 'Night street food stall in Lagos, charcoal grill glowing orange, skewered suya meat sizzling, smoke wisps, close-up hands of food vendor with skill and speed, rain-wet asphalt reflecting light, crowd background',
    captionTemplate: '{food_name} at {location} hitting different tonight 🔥\n\n₦{price} and it\'s worth every kobo.\n\nWhere\'s your favourite street food spot? 👇\n\nComment your city!',
    hashtags: ['streetfood', 'naijafood', 'asmrfood', 'lagosfoodies', 'nigerianfood', 'suya', 'foodtiktok'],
    estimatedViews: '100K - 8M',
    bestTime: '7pm - 10pm',
    emoji: '🍢',
  },
  {
    id: 'danfo-experience',
    name: 'The Danfo Experience',
    category: 'street_life',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'Boarding a Lagos danfo is a full spiritual experience. Let me explain.',
    structure: [
      'Quick chaotic cut of danfo rushing to stop',
      'Conductor shouting destinations',
      'Squeezing into seat (relatable)',
      'In-bus atmosphere (arguments, hawkers, random prayers)',
      'Finally arriving — exhausted but alive',
    ],
    visualPrompt: 'Yellow and black Lagos danfo minibus, busy traffic intersection, sweaty passengers, hawkers with trays through window, conductor hanging off door, chaotic beautiful Lagos commute, documentary style',
    captionTemplate: 'Lagos danfo is not transportation. It\'s a WHOLE experience. 😂\n\n{funny_moment}\n\nThe conductor had the AUDACITY to— 😭\n\nLagos people, which danfo route traumatised you? 👇',
    hashtags: ['danfo', 'lagoslife', 'naijatiktok', 'lagostransport', 'lagoshustle', 'onlyinlagos'],
    estimatedViews: '200K - 5M',
    bestTime: '12pm - 3pm',
    emoji: '🚌',
  },
  {
    id: 'market-day-chaos',
    name: 'Nigerian Market Day',
    category: 'street_life',
    platform: ['tiktok', 'youtube', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'Balogun Market is not a market. It\'s a whole civilization.',
    structure: [
      'Wide drone shot of market from above',
      'Walk-through POV with ambient noise',
      'Haggling scene (playful tension)',
      'Unexpected discovery (rare item / hidden store)',
      'Callback to original item — final price reveal',
    ],
    visualPrompt: 'Aerial shot of Balogun Market Lagos, densely packed stalls, colorful fabrics and goods, thousands of traders and buyers, chaotic organized energy, warm afternoon sun, rich saturated colors',
    captionTemplate: 'I went to {market} for ONE thing. Left with EVERYTHING. 😭\n\nThe way market women will negotiate your entire wallet away...\n\n{funny_exchange}\n\nTag someone who "just wants to browse" 👇',
    hashtags: ['nigerianmarket', 'balogunmarket', 'lagosmarket', 'naijashopping', 'marketday', 'africanmarket'],
    estimatedViews: '80K - 3M',
    bestTime: '11am - 2pm',
    emoji: '🛍️',
  },

  // ─── Afrobeats / Music Content ────────────────────────────────────
  {
    id: 'afrobeats-sync',
    name: 'Afrobeats Sync Video',
    category: 'afrobeats',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'When the Afrobeats drops and your body just... knows.',
    structure: [
      'Normal/neutral scene',
      'Beat drops — immediate energy shift',
      'Dance/reaction sync to music',
      'Quick outfit change or location change on beat',
      'Peak energy moment at chorus',
    ],
    visualPrompt: 'Young Nigerian dancing in stylish Ankara outfit, outdoor Lagos location, golden sunset, neon city lights at night, slow-motion hair flip, vibrant warm colors, music video aesthetic, professional cinematography',
    captionTemplate: 'When {artist} drops a new song and you leave the meeting early 😂🎵\n\nThis beat is {adjective}!\n\nWho else is in their {artist} era? 👇\n\n#afrobeats #naijababy',
    hashtags: ['afrobeats', 'naijababy', 'afropop', 'nigerianmusic', 'dancechallenge', 'afrobeatchallenge'],
    estimatedViews: '500K - 20M',
    bestTime: '6pm - 10pm',
    emoji: '🎵',
  },
  {
    id: 'concert-recap',
    name: 'Concert / Show Recap',
    category: 'afrobeats',
    platform: ['instagram', 'tiktok', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: 'Burna Boy\'s concert last night changed something in my soul.',
    structure: [
      'Crowd shot — energy establishing',
      'Artist performance highlights',
      'Personal reaction close-up',
      'Best song moment',
      'Post-show reflection or meet-and-greet',
    ],
    visualPrompt: 'Outdoor concert in Lagos under stadium lights, massive crowd, artist on stage with light show, phone torches lighting up, smoke machines, electric atmosphere, festival aesthetic, high energy',
    captionTemplate: '{artist} concert was {reaction} 🔥🎤\n\n{highlight_moment}\n\nIf you were there, you understand. If you weren\'t — I\'m sorry for your loss.\n\n{cta}',
    hashtags: ['afrobeatsconcert', 'naijaconcert', 'lagosturntup', 'concertvibes', 'livemusic'],
    estimatedViews: '50K - 2M',
    bestTime: '10pm - 1am',
    emoji: '🎤',
  },

  // ─── Tech & Digital Hustle ────────────────────────────────────────
  {
    id: 'tech-nigeria-review',
    name: 'Nigerian Tech Review',
    category: 'hustle',
    platform: ['youtube', 'tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'I tested {app/product} for 30 days in Nigeria. Honest review.',
    structure: [
      'Unboxing or first use moment',
      'Context: "This is how it works in Nigeria specifically"',
      'Problem it solves (local context)',
      'What works vs what doesn\'t',
      'Final verdict with Nigerian pricing/availability info',
    ],
    visualPrompt: 'Clean Nigerian tech creator setup, ring light, professional desk, laptop and phone in frame, modern Lagos apartment background, tech review aesthetic, branded B-roll of product in use',
    captionTemplate: '🇳🇬 Nigerian Review: {product}\n\nEveryone overseas is hyping this but here\'s the TRUTH for Naija users:\n\n✅ {pro_1}\n✅ {pro_2}\n❌ {con_1}\n❌ {con_2}\n\nIs it worth it? {verdict}\n\nComments: have you tried it?',
    hashtags: ['nigeriantech', 'naijatechreview', 'techinnigeria', 'nigeriastartup', 'techreview'],
    estimatedViews: '20K - 500K',
    bestTime: '9am - 12pm',
    emoji: '📱',
  },
  {
    id: 'freelance-naija',
    name: 'Freelancing in Nigeria Guide',
    category: 'hustle',
    platform: ['youtube', 'tiktok', 'linkedin'],
    contentType: 'video',
    tier: 'free',
    hook: 'I made $3,000 last month freelancing from my room in Ibadan.',
    structure: [
      'Income proof (screenshot or graph)',
      'The skill they used (specific, not vague)',
      'How they found clients (Upwork, Twitter, referrals)',
      'Nigeria-specific challenges + solutions (payment, power)',
      'Actionable first step for viewers',
    ],
    visualPrompt: 'Young Nigerian professional at laptop in modern apartment, multiple income screens visible, professional but personal atmosphere, natural window light, confident relaxed pose',
    captionTemplate: '🇳🇬 I made ${amount} this month from my room in {city}.\n\nHere\'s exactly how (no BS):\n\n1. {skill}\n2. {platform}\n3. {first_client_strategy}\n\nThe hardest part? {challenge}\n\nDM me "FREELANCE" and I\'ll send you the free guide 📩',
    hashtags: ['freelancenigeria', 'dollarearner', 'naijahustle', 'remotework', 'nigerianfreelancer', 'makemoneyonline'],
    estimatedViews: '30K - 1M',
    bestTime: '8am - 11am',
    emoji: '💻',
  },

  // ─── Fashion & Style ──────────────────────────────────────────────
  {
    id: 'ankara-fashion-drop',
    name: 'Ankara Fashion Drop',
    category: 'naija_culture',
    platform: ['instagram', 'tiktok'],
    contentType: 'video',
    tier: 'free',
    hook: 'New ankara collection just dropped and I CANNOT.',
    structure: [
      'Fabric reveal — tactile close-up',
      'Fitting montage (3-5 outfits)',
      'Styling tips for each look',
      'Price and where to buy',
      'CTA: "Which is your favourite?"',
    ],
    visualPrompt: 'Nigerian fashion model in vibrant Ankara print outfit, Lagos skyline background, golden hour photography, bold pattern close-ups, editorial fashion shoot aesthetic, rich jewel tones, African accessories',
    captionTemplate: '✨ New collection is HERE and I\'m obsessed.\n\nAnkara {style_name} — perfect for {occasion}\n\n📍 Available at {location}\n💰 From ₦{price}\n\nWhich colour? Drop your fav below 👇🧡',
    hashtags: ['ankara', 'ankarafashion', 'naijafashion', 'africanfashion', 'owanbe', 'nigeriandesigner'],
    estimatedViews: '30K - 800K',
    bestTime: '12pm - 4pm',
    emoji: '👗',
  },
  {
    id: 'owambe-outfit',
    name: 'Owambe Outfit Reveal',
    category: 'naija_culture',
    platform: ['instagram', 'tiktok'],
    contentType: 'video',
    tier: 'free',
    hook: 'Owambe season is here and I\'m not coming to play.',
    structure: [
      'Getting ready montage (early stages)',
      'Final reveal — full look',
      'Accessory close-ups',
      'Twirl/pose moment',
      'Tag your owanbe squad CTA',
    ],
    visualPrompt: 'Nigerian woman in stunning agbada or lace outfit for owambe party, professional makeup, gele headtie, statement jewelry, warm indoor party venue, Lagos socialite aesthetic, golden accents',
    captionTemplate: 'Owambe ready or owambe ready? 😍🎊\n\nOutfit details:\n👗 Fabric: {fabric}\n💄 MUA: {makeup_artist}\n💍 Jewelry: {jewelry}\n📍 Event: {event_type}\n\nTag your owanbe partner in crime 👇',
    hashtags: ['owambe', 'naijagirl', 'asoebi', 'nigerianwedding', 'lagossocialite', 'naijafashion', 'gele'],
    estimatedViews: '50K - 2M',
    bestTime: '10am - 2pm',
    emoji: '👑',
  },

  // ─── Real Estate & Properties ─────────────────────────────────────
  {
    id: 'real-estate-flex',
    name: 'Nigerian Property Tour',
    category: 'hustle',
    platform: ['instagram', 'youtube', 'tiktok'],
    contentType: 'video',
    tier: 'basic',
    hook: 'This 3-bedroom apartment in Lekki is going for ₦4.5M/year. Let\'s tour.',
    structure: [
      'Exterior establishing shot',
      'Room-by-room walkthrough with commentary',
      'Standout feature moment ("look at this...")',
      'Price and value comparison',
      'CTA: How to enquire',
    ],
    visualPrompt: 'Modern Nigerian apartment in Lekki or Victoria Island, clean bright interiors, marble floors, Lagos lagoon view from balcony, luxury real estate photography, wide angle architectural shots',
    captionTemplate: '🏠 {property_type} | {location} | ₦{price}/year\n\n{key_feature_1}\n{key_feature_2}\n{key_feature_3}\n\nLet\'s talk about this Lagos real estate market though... 👀\n\nDM "INTERESTED" for full details 📩\n\nSave for your house goals! 🔖',
    hashtags: ['lagosrealestate', 'nigerianproperty', 'lekki', 'nigerianhouses', 'nigeriapropertymarket', 'househunting'],
    estimatedViews: '30K - 1M',
    bestTime: '10am - 1pm',
    emoji: '🏠',
  },

  // ─── Sports Content ───────────────────────────────────────────────
  {
    id: 'super-eagles-hype',
    name: 'Super Eagles Hype Video',
    category: 'naija_culture',
    platform: ['tiktok', 'instagram', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: 'Super Eagles matchday and the whole country stops.',
    structure: [
      'Pre-match energy — streets, watch parties',
      'Player highlights montage',
      'Crowd reaction at key moment',
      'Post-match celebrations or commentary',
      'Green-white-green flag moment',
    ],
    visualPrompt: 'Nigerian football crowd in green and white jerseys, outdoor street viewing center Lagos, massive screen, fans jumping and celebrating, Nigerian flag waving, emotional reaction shots, sports documentary style',
    captionTemplate: '🇳🇬 SUPER EAGLES 🦅\n\n{match_result}\n\n{player_name} tonight was DIFFERENT. The way he— 😤\n\nNigeria till I die. Comment your player ratings below 👇\n\n{match_hashtag}',
    hashtags: ['supereagles', 'nigeria', 'afcon', 'nigerianfootball', 'wearethesupereagle', 'naijafootball'],
    estimatedViews: '200K - 10M',
    bestTime: 'Matchday +2hr',
    emoji: '⚽',
  },

  // ─── Food Content ─────────────────────────────────────────────────
  {
    id: 'naija-recipe',
    name: 'Nigerian Recipe Tutorial',
    category: 'naija_culture',
    platform: ['youtube', 'tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'Making jollof rice that will make your mother cry with jealousy.',
    structure: [
      'Ingredients laid out — visual appeal',
      'Step-by-step cooking (fast cuts)',
      'The signature moment (the char, the steam, the colour)',
      'Taste test reaction',
      'Final plated shot with natural light',
    ],
    visualPrompt: 'Nigerian kitchen with authentic ingredients, bright red tomato stew base, aromatic steam rising from pot, jollof rice with perfect smoky bottom, professional food photography style, warm kitchen lighting, authentic home setting',
    captionTemplate: '🍛 {recipe_name} Recipe (No Measurements Needed)\n\nIngredients:\n{ingredients_list}\n\nThe SECRET to that smoky bottom? {tip}\n\nSave this before your next owambe! 🔖\n\nDrop "RECIPE" for the full written version 👇',
    hashtags: ['jollofrice', 'naijafood', 'nigerianrecipe', 'africancooking', 'foodtok', 'naijachef'],
    estimatedViews: '50K - 3M',
    bestTime: '12pm - 2pm',
    emoji: '🍛',
  },
  {
    id: 'food-review-lagos',
    name: 'Lagos Restaurant Review',
    category: 'street_life',
    platform: ['instagram', 'youtube', 'tiktok'],
    contentType: 'video',
    tier: 'free',
    hook: 'I spent ₦45,000 at this Lekki restaurant. Was it worth it?',
    structure: [
      'Restaurant entrance/ambiance',
      'Menu highlight (price context)',
      'Food arrival — visual wow moment',
      'Honest taste reaction',
      'Rating out of 10 + verdict',
    ],
    visualPrompt: 'Upscale Nigerian restaurant in Lekki Lagos, beautifully plated Nigerian fusion cuisine, ambient warm lighting, elegant African decor, food blogger aesthetic, clean editorial photography',
    captionTemplate: '🍽️ Honest Review: {restaurant_name}, {location}\n\nI ordered:\n• {dish_1} — ₦{price_1}\n• {dish_2} — ₦{price_2}\n\nThe {best_dish}? UNREAL. The {disappointing_thing}? Hmm...\n\nWorth it? {rating}/10\n\nHave you been? Drop your experience 👇',
    hashtags: ['lagosrestaurant', 'nigerianfood', 'lagoseats', 'foodreview', 'lagosfoodguide', 'wheretoeat'],
    estimatedViews: '30K - 1M',
    bestTime: '1pm - 4pm',
    emoji: '🍽️',
  },

  // ─── Spiritual / Motivational ─────────────────────────────────────
  {
    id: 'prayer-warrior',
    name: 'Early Morning Motivation',
    category: 'naija_culture',
    platform: ['instagram', 'facebook', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: '4am and I\'m already winning. Here\'s why...',
    structure: [
      'Pre-dawn establishing shot — quiet and still',
      'Morning routine — prayer, study, movement',
      'Affirmation/scripture that grounds the content',
      'Practical goal/intention for the day',
      'Close with blessing or activation',
    ],
    visualPrompt: 'Early morning Lagos, orange dawn sky, person in prayer or quiet reflection, soft golden light through window, Bible or journal nearby, peaceful private moment, warm faith-filled aesthetic',
    captionTemplate: 'Before the world wakes up, I\'m already positioning myself. 🙏\n\n{scripture_or_quote}\n\nToday I\'m declaring:\n✨ {declaration_1}\n✨ {declaration_2}\n✨ {declaration_3}\n\nSay "Amen" if this is yours today 🔥',
    hashtags: ['morningmotivation', 'naijachristian', 'faith', 'godsgirl', 'nigerianfaith', 'dailydevotion', 'blessed'],
    estimatedViews: '20K - 500K',
    bestTime: '5am - 8am',
    emoji: '🙏',
  },
  {
    id: 'naija-soft-life',
    name: 'Soft Life Aesthetic',
    category: 'naija_culture',
    platform: ['instagram', 'tiktok'],
    contentType: 'video',
    tier: 'free',
    hook: 'Soft life is not laziness. It\'s choosing peace deliberately.',
    structure: [
      'Luxurious calm opening — spa, pool, nice view',
      'Self-care ritual in detail',
      'The "this is what I chose instead" moment',
      'Peaceful reflection or affirmation',
      'Invite viewers into their own soft life',
    ],
    visualPrompt: 'Nigerian woman in luxury hotel or beautiful Lagos apartment, rooftop infinity pool, afternoon light, silk robe, fresh flowers, premium Nigerian aesthetic, calm and aspirational, Lagos skyline visible',
    captionTemplate: 'I chose {choice} over {alternative} and I\'d do it again. 🌸\n\nSoft life isn\'t a trend. It\'s a standard I set for myself.\n\n{soft_life_moment}\n\nWhat\'s your soft life definition? 👇',
    hashtags: ['softlife', 'naijagirl', 'selfcare', 'lagossoftlife', 'luxurylifestyle', 'selfcarenaija'],
    estimatedViews: '80K - 3M',
    bestTime: '2pm - 6pm',
    emoji: '🌸',
  },

  // ─── Educational ─────────────────────────────────────────────────
  {
    id: 'naija-money-lesson',
    name: 'Nigerian Money Education',
    category: 'educational',
    platform: ['tiktok', 'instagram', 'youtube'],
    contentType: 'video',
    tier: 'free',
    hook: 'Why most Nigerians stay broke even when earning good money.',
    structure: [
      'Relatable money mistake (personal or observed)',
      'The financial concept explained simply',
      'Nigeria-specific context (inflation, FX, savings)',
      'What to do instead (actionable)',
      'Challenge: "Try this for 30 days"',
    ],
    visualPrompt: 'Nigerian professional at desk with financial graphs, naira notes and dollar notes, white board with simple diagrams, educational presenter style, modern clean Nigerian office aesthetic',
    captionTemplate: '💰 Nobody tells young Nigerians this about money:\n\n{main_lesson}\n\nThe inflation eating your savings?\n{inflation_tip}\n\nThe dollar strategy that actually works in Nigeria:\n{strategy}\n\nSave this. Thank me in 6 months. 🔖',
    hashtags: ['nigerianfinance', 'moneynaija', 'financialnaija', 'nairaeducation', 'investinnigeria', 'personalfinancenigeria'],
    estimatedViews: '40K - 2M',
    bestTime: '9am - 12pm',
    emoji: '💰',
  },
  {
    id: 'edu-did-you-know',
    name: 'Did You Know Fact Drop',
    category: 'educational',
    platform: ['tiktok', 'instagram', 'twitter', 'linkedin'],
    contentType: 'both',
    tier: 'free',
    hook: 'Did you know {surprising fact}? 🤯',
    structure: ['Surprising fact hook', 'Quick context (why it matters)', 'Related fact cascade', 'Practical takeaway', 'Follow for more'],
    visualPrompt: 'Clean educational infographic style, bold typography, minimal background, animated text reveals, satisfying color palette',
    captionTemplate: 'Did you know {fact}? 🤯\n\n{explanation}\n\nFollow for daily facts that will blow your mind 🧠',
    hashtags: ['didyouknow', 'facts', 'learnontiktok', 'educational', 'mindblown'],
    estimatedViews: '10K - 500K',
    bestTime: '9am - 12pm',
    emoji: '🤯',
  },

  // ─── Product Launch ──────────────────────────────────────────────
  {
    id: 'product-cinematic-reveal',
    name: 'Cinematic Product Reveal',
    category: 'product_launch',
    platform: ['instagram', 'youtube', 'tiktok'],
    contentType: 'video',
    tier: 'basic',
    hook: 'Something BIG is coming...',
    structure: ['Dark screen / mystery open', 'Slow product reveal with music drop', 'Feature highlights (3 max)', 'Price reveal + CTA'],
    visualPrompt: 'Cinematic product reveal, dark studio, dramatic spotlight, slow zoom, luxury aesthetic, 4K sharp details, premium packaging',
    captionTemplate: '✨ Introducing {product_name} ✨\n\n{tagline}\n\n🎯 {feature_1}\n🎯 {feature_2}\n🎯 {feature_3}\n\nLink in bio to get yours! 🔗',
    hashtags: ['newproduct', 'launch', 'comingsoon', 'innovation'],
    estimatedViews: '5K - 100K',
    bestTime: '9am - 11am',
    emoji: '🚀',
  },
  {
    id: 'product-before-after',
    name: 'Before / After Transformation',
    category: 'product_launch',
    platform: ['instagram', 'tiktok', 'facebook'],
    contentType: 'both',
    tier: 'free',
    hook: 'I tried {product} for 30 days. Here\'s what happened...',
    structure: ['Show the "before" state (relatable problem)', 'Build tension / show struggle', 'Introduce the product as solution', 'Dramatic after results', 'CTA with offer'],
    visualPrompt: 'Split-screen transformation, left side muted colors for "before", right side vibrant warm tones for "after", clean modern aesthetic',
    captionTemplate: 'Before vs After using {product} for 30 days 😱\n\n{transformation_story}\n\nSwipe to see the full results ➡️\n\n{cta}',
    hashtags: ['beforeandafter', 'transformation', 'results', 'glow'],
    estimatedViews: '15K - 800K',
    bestTime: '6pm - 9pm',
    emoji: '✨',
  },

  // ─── Tutorial ────────────────────────────────────────────────────
  {
    id: 'tutorial-5-steps',
    name: '5 Steps Tutorial',
    category: 'tutorial',
    platform: ['youtube', 'instagram', 'tiktok', 'linkedin'],
    contentType: 'video',
    tier: 'free',
    hook: '5 steps to {outcome} in {timeframe}',
    structure: ['Hook with end result', 'Step 1 (with visual)', 'Step 2', 'Step 3', 'Step 4', 'Step 5 + reveal', 'CTA: "Save this for later"'],
    visualPrompt: 'Clean minimal tutorial style, step counter animation, clear text overlays, bright professional lighting, screen recording style',
    captionTemplate: '5 steps to {outcome} 🎯\n\n1️⃣ {step_1}\n2️⃣ {step_2}\n3️⃣ {step_3}\n4️⃣ {step_4}\n5️⃣ {step_5}\n\nSave this! You\'ll thank me later 🔖',
    hashtags: ['tutorial', 'howto', 'tips', 'learn', 'education'],
    estimatedViews: '8K - 200K',
    bestTime: '8am - 10am',
    emoji: '📚',
  },
  {
    id: 'tutorial-hack-reveal',
    name: 'Hack Reveal',
    category: 'tutorial',
    platform: ['tiktok', 'instagram', 'twitter'],
    contentType: 'video',
    tier: 'free',
    hook: '{number} {topic} hacks that actually work',
    structure: ['Fast-cut hacks sequence', 'Each hack 3-5 seconds', 'Reaction shot between hacks', 'Most impressive hack last', 'CTA overlay'],
    visualPrompt: 'Fast-cut montage style, energy-driven, quick transitions, bright colors, satisfying reveals, trending meme aesthetic',
    captionTemplate: '{number} {topic} hacks nobody told you about 🤯\n\n(Save before it\'s deleted)\n\nWhich one surprised you? 👇',
    hashtags: ['hacks', 'tips', 'lifehacks', 'mindblown', 'viral'],
    estimatedViews: '20K - 5M',
    bestTime: '3pm - 7pm',
    emoji: '⚡',
  },

  // ─── Behind the Scenes ───────────────────────────────────────────
  {
    id: 'bts-day-in-life',
    name: 'Day in My Life',
    category: 'behind_scenes',
    platform: ['youtube', 'tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'A day in the life of a {job/lifestyle}',
    structure: ['Morning routine (relatable)', 'Work behind scenes', 'Challenges moment (authentic)', 'Evening wind down', 'Reflection + invite to follow'],
    visualPrompt: 'Vlog aesthetic, warm golden hour lighting, casual handheld camera style, lifestyle photography, authentic candid moments',
    captionTemplate: 'Day in my life as a {role} ☀️\n\n{story}\n\nFollow for more behind the scenes ✨',
    hashtags: ['dayinmylife', 'vlog', 'behindthescenes', 'lifestyle', 'content'],
    estimatedViews: '5K - 150K',
    bestTime: '5pm - 8pm',
    emoji: '🎥',
  },
  {
    id: 'bts-creative-process',
    name: 'Behind the Creative',
    category: 'behind_scenes',
    platform: ['instagram', 'youtube', 'tiktok'],
    contentType: 'video',
    tier: 'free',
    hook: 'What making viral content actually looks like at 2am.',
    structure: [
      'Raw unfiltered workspace shot',
      'Process in action (not polished)',
      'The mistake or challenge moment',
      'Final result vs messy process',
      'The work behind the work narrative',
    ],
    visualPrompt: 'Content creator working at night, multiple screens, ring light, slightly chaotic creative workspace, authentic behind-scenes energy, blue-white laptop glow in dark room',
    captionTemplate: 'Everyone sees the {result}.\nNobody sees the {process}. 🎬\n\n{honest_moment}\n\nThe algorithm doesn\'t care how tired you are.\nBut I do. 🫶\n\nCreator, how are you REALLY doing? 👇',
    hashtags: ['contentcreator', 'behindthescenes', 'creatorlife', 'contentcreation', 'naijacreator'],
    estimatedViews: '10K - 300K',
    bestTime: '9pm - 12am',
    emoji: '🎬',
  },

  // ─── Trending ────────────────────────────────────────────────────
  {
    id: 'trending-af1',
    name: 'Tell Me Without Telling Me',
    category: 'trending',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'Tell me you\'re a {identity} without telling me you\'re a {identity}',
    structure: ['Text prompt on screen', 'Fast-cut "evidence" clips', 'Relatable payoff moment', 'Comment bait at end'],
    visualPrompt: 'Trendy aesthetic, quick cuts, relatable scenarios, TikTok native style, text overlays, trending audio placement',
    captionTemplate: 'Tell me you\'re a {identity} without telling me you\'re a {identity} 😂\n\n{content}\n\nTag a {identity} in the comments! 👇',
    hashtags: ['tellmewithout', 'relatable', 'fyp', 'foryoupage', 'trending'],
    estimatedViews: '25K - 3M',
    bestTime: '7pm - 11pm',
    emoji: '😂',
  },
  {
    id: 'trending-naija-vibe-check',
    name: 'Naija Vibe Check',
    category: 'trending',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'Rate your week: Lagos edition 😂',
    structure: [
      'Quick setup of relatable Nigerian scenario',
      'Fast-cut reacting to 5 scenarios (rate 1-10)',
      'Most ridiculous one saved for last',
      'Trend audio playing throughout',
    ],
    visualPrompt: 'Young Nigerians reacting to relatable everyday scenarios, quick comedy cuts, Lagos setting, natural lighting, authentic reactions, trending format energy',
    captionTemplate: 'NAIJA VIBE CHECK ✅\n\n{scenario_1}: {rating}/10\n{scenario_2}: {rating}/10\n{scenario_3}: {rating}/10\n\nRate your week below 👇\n\nAnd if NEPA took light during {moment} — automatic 0/10 😭',
    hashtags: ['naijavibe', 'naijatiktok', 'lagoslife', 'naijareaction', 'relatablenaija'],
    estimatedViews: '100K - 5M',
    bestTime: '4pm - 8pm',
    emoji: '✅',
  },

  // ─── Challenge ───────────────────────────────────────────────────
  {
    id: 'challenge-7-day',
    name: '7-Day Challenge',
    category: 'challenge',
    platform: ['tiktok', 'instagram', 'youtube'],
    contentType: 'video',
    tier: 'basic',
    hook: 'I did {challenge} for 7 days. The results shocked me.',
    structure: ['Day 0: Starting point (vulnerable)', 'Day 1-3: Struggles (authentic)', 'Day 4-5: Turning point', 'Day 6-7: Results', 'Final transformation reveal'],
    visualPrompt: 'Day counter overlay, before/after split, progress timeline visualization, raw authentic aesthetic, emotional color grade',
    captionTemplate: '7-day {challenge} results 📅\n\nDay 1: {start}\nDay 7: {result}\n\nThe thing nobody tells you about {topic}... {insight}\n\nWho else tried this? Comment your experience 👇',
    hashtags: ['7daychallenge', 'challenge', 'transformation', 'results', 'journey'],
    estimatedViews: '20K - 1M',
    bestTime: '5pm - 9pm',
    emoji: '💪',
  },
  {
    id: 'challenge-no-spend',
    name: 'No-Spend Challenge',
    category: 'challenge',
    platform: ['tiktok', 'instagram'],
    contentType: 'video',
    tier: 'free',
    hook: 'I\'m doing a 30-day no-spend challenge in Lagos. Day 1.',
    structure: [
      'Day 1 declaration + bank balance reveal',
      'Temptation moments (Lagos makes it hard)',
      'Free alternative strategies discovered',
      'Week check-in with savings',
      'Final day — total saved',
    ],
    visualPrompt: 'Young Nigerian tracking expenses on phone, resisting temptation at market stalls and restaurants, wallet deliberately closed, determination and humor in expressions, Lagos backdrop',
    captionTemplate: 'Day {day} of no-spending in Lagos 💸\n\nTemptations survived:\n❌ {temptation_1}\n❌ {temptation_2}\n\nCurrent savings: ₦{amount}\n\nSomeone DM me suya right now and I will not be held responsible 😭\n\nAre you doing this with me? 👇',
    hashtags: ['nospenddchallenge', 'savingmoney', 'nairanaira', 'financechallenge', 'lagoslifestyle'],
    estimatedViews: '30K - 800K',
    bestTime: '7am - 10am',
    emoji: '💸',
  },

  // ─── Testimonials ────────────────────────────────────────────────
  {
    id: 'testimonial-client-win',
    name: 'Client Win Story',
    category: 'testimonial',
    platform: ['linkedin', 'instagram', 'facebook'],
    contentType: 'both',
    tier: 'basic',
    hook: '{client} went from {before} to {after} in {timeframe}',
    structure: ['Client\'s before state (relatable problem)', 'What they tried before (and failed)', 'How your solution helped', 'Specific measurable results', 'Client quote', 'Offer + CTA'],
    visualPrompt: 'Professional success story design, client photo or avatar, achievement metric highlighted, warm success tones, corporate-casual aesthetic',
    captionTemplate: '🎉 Client win: {client_name} achieved {result} in just {timeframe}!\n\n"{testimonial_quote}"\n— {client_name}, {client_title}\n\nHow we did it:\n{strategy}\n\nWant results like this? DM me "WIN" 🏆',
    hashtags: ['clientwin', 'results', 'success', 'testimonial', 'proof'],
    estimatedViews: '2K - 30K',
    bestTime: '9am - 11am',
    emoji: '🏆',
  },

  // ─── Promo / Sales ───────────────────────────────────────────────
  {
    id: 'promo-urgency-offer',
    name: 'Limited Time Offer',
    category: 'promo',
    platform: ['instagram', 'facebook', 'twitter'],
    contentType: 'image',
    tier: 'basic',
    hook: '⚠️ This deal expires in 24 hours',
    structure: ['Urgency headline', 'What they get', 'Price before/after', 'Testimonial snippet', 'CTA button'],
    visualPrompt: 'Bold sales graphic, countdown timer visual, vibrant contrast colors, urgency typography, price reveal spotlight, high-energy promotional design',
    captionTemplate: '⚠️ LAST CHANCE: {offer} ends tonight at midnight!\n\n✅ {benefit_1}\n✅ {benefit_2}\n✅ {benefit_3}\n\nNormal price: ~~{old_price}~~\nYOURS TODAY: {new_price}\n\n🔗 Link in bio | DM "YES" to claim',
    hashtags: ['sale', 'offer', 'deal', 'limitedtime', 'discount'],
    estimatedViews: '3K - 50K',
    bestTime: '12pm - 3pm',
    emoji: '🔥',
  },
]

// ─── Helper functions ─────────────────────────────────────────────────────

export function getTemplatesByPlatform(platform: SocialPlatform): ContentTemplate[] {
  return TEMPLATE_LIBRARY.filter(t => t.platform.includes(platform))
}

export function getTemplatesByCategory(category: TemplateCategory): ContentTemplate[] {
  return TEMPLATE_LIBRARY.filter(t => t.category === category)
}

export function getTemplateById(id: string): ContentTemplate | undefined {
  return TEMPLATE_LIBRARY.find(t => t.id === id)
}

export function fillTemplate(template: ContentTemplate, vars: Record<string, string>): {
  caption: string; hashtags: string[]
} {
  let caption = template.captionTemplate
  for (const [key, value] of Object.entries(vars)) {
    caption = caption.replace(new RegExp(`{${key}}`, 'g'), value)
  }
  return { caption, hashtags: template.hashtags }
}
